// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: econ_shared_enums.proto
// Protobuf C++ Version: 5.27.3

#include "econ_shared_enums.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr CMsgGenericResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        debug_message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        eresult_{2u} {}

template <typename>
PROTOBUF_CONSTEXPR CMsgGenericResult::CMsgGenericResult(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CMsgGenericResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CMsgGenericResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgGenericResultDefaultTypeInternal() {}
  union {
    CMsgGenericResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgGenericResultDefaultTypeInternal _CMsgGenericResult_default_instance_;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_econ_5fshared_5fenums_2eproto[3];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_econ_5fshared_5fenums_2eproto = nullptr;
const ::uint32_t
    TableStruct_econ_5fshared_5fenums_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::CMsgGenericResult, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::CMsgGenericResult, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::CMsgGenericResult, _impl_.eresult_),
        PROTOBUF_FIELD_OFFSET(::CMsgGenericResult, _impl_.debug_message_),
        1,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::CMsgGenericResult)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_CMsgGenericResult_default_instance_._instance,
};
const char descriptor_table_protodef_econ_5fshared_5fenums_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\027econ_shared_enums.proto\">\n\021CMsgGeneric"
    "Result\022\022\n\007eresult\030\001 \001(\r:\0012\022\025\n\rdebug_mess"
    "age\030\002 \001(\t*,\n\016EGCEconBaseMsg\022\032\n\025k_EMsgGCG"
    "enericResult\020\223\024*\233\002\n\016EGCMsgResponse\022\026\n\022k_"
    "EGCMsgResponseOK\020\000\022\032\n\026k_EGCMsgResponseDe"
    "nied\020\001\022\037\n\033k_EGCMsgResponseServerError\020\002\022"
    "\033\n\027k_EGCMsgResponseTimeout\020\003\022\033\n\027k_EGCMsg"
    "ResponseInvalid\020\004\022\033\n\027k_EGCMsgResponseNoM"
    "atch\020\005\022 \n\034k_EGCMsgResponseUnknownError\020\006"
    "\022\037\n\033k_EGCMsgResponseNotLoggedOn\020\007\022\032\n\026k_E"
    "GCMsgFailedToCreate\020\010*\305\005\n\025EGCMsgUseItemR"
    "esponse\022$\n k_EGCMsgUseItemResponse_ItemU"
    "sed\020\000\022.\n*k_EGCMsgUseItemResponse_GiftNoO"
    "therPlayers\020\001\022\'\n#k_EGCMsgUseItemResponse"
    "_ServerError\020\002\0222\n.k_EGCMsgUseItemRespons"
    "e_MiniGameAlreadyStarted\020\003\0221\n-k_EGCMsgUs"
    "eItemResponse_ItemUsed_ItemsGranted\020\004\0227\n"
    "3k_EGCMsgUseItemResponse_DropRateBonusAl"
    "readyGranted\020\005\0220\n,k_EGCMsgUseItemRespons"
    "e_NotInLowPriorityPool\020\006\022.\n*k_EGCMsgUseI"
    "temResponse_NotHighEnoughLevel\020\007\022*\n&k_EG"
    "CMsgUseItemResponse_EventNotActive\020\010\0227\n3"
    "k_EGCMsgUseItemResponse_ItemUsed_EventPo"
    "intsGranted\020\t\022.\n*k_EGCMsgUseItemResponse"
    "_MissingRequirement\020\n\0220\n,k_EGCMsgUseItem"
    "Response_EmoticonUnlock_NoNew\020\013\0223\n/k_EGC"
    "MsgUseItemResponse_EmoticonUnlock_Comple"
    "te\020\014\022/\n+k_EGCMsgUseItemResponse_ItemUsed"
    "_Compendium\020\r"
};
static ::absl::once_flag descriptor_table_econ_5fshared_5fenums_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_econ_5fshared_5fenums_2eproto = {
    false,
    false,
    1133,
    descriptor_table_protodef_econ_5fshared_5fenums_2eproto,
    "econ_shared_enums.proto",
    &descriptor_table_econ_5fshared_5fenums_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_econ_5fshared_5fenums_2eproto::offsets,
    file_level_enum_descriptors_econ_5fshared_5fenums_2eproto,
    file_level_service_descriptors_econ_5fshared_5fenums_2eproto,
};
const ::google::protobuf::EnumDescriptor* EGCEconBaseMsg_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_econ_5fshared_5fenums_2eproto);
  return file_level_enum_descriptors_econ_5fshared_5fenums_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t EGCEconBaseMsg_internal_data_[] = {
    68115u, 0u, };
bool EGCEconBaseMsg_IsValid(int value) {
  return 2579 <= value && value <= 2579;
}
const ::google::protobuf::EnumDescriptor* EGCMsgResponse_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_econ_5fshared_5fenums_2eproto);
  return file_level_enum_descriptors_econ_5fshared_5fenums_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t EGCMsgResponse_internal_data_[] = {
    589824u, 0u, };
bool EGCMsgResponse_IsValid(int value) {
  return 0 <= value && value <= 8;
}
const ::google::protobuf::EnumDescriptor* EGCMsgUseItemResponse_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_econ_5fshared_5fenums_2eproto);
  return file_level_enum_descriptors_econ_5fshared_5fenums_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t EGCMsgUseItemResponse_internal_data_[] = {
    917504u, 0u, };
bool EGCMsgUseItemResponse_IsValid(int value) {
  return 0 <= value && value <= 13;
}
// ===================================================================

class CMsgGenericResult::_Internal {
 public:
  using HasBits =
      decltype(std::declval<CMsgGenericResult>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CMsgGenericResult, _impl_._has_bits_);
};

CMsgGenericResult::CMsgGenericResult(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CMsgGenericResult)
}
inline PROTOBUF_NDEBUG_INLINE CMsgGenericResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::CMsgGenericResult& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        debug_message_(arena, from.debug_message_) {}

CMsgGenericResult::CMsgGenericResult(
    ::google::protobuf::Arena* arena,
    const CMsgGenericResult& from)
    : ::google::protobuf::Message(arena) {
  CMsgGenericResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.eresult_ = from._impl_.eresult_;

  // @@protoc_insertion_point(copy_constructor:CMsgGenericResult)
}
inline PROTOBUF_NDEBUG_INLINE CMsgGenericResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        debug_message_(arena),
        eresult_{2u} {}

inline void CMsgGenericResult::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CMsgGenericResult::~CMsgGenericResult() {
  // @@protoc_insertion_point(destructor:CMsgGenericResult)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CMsgGenericResult::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.debug_message_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
CMsgGenericResult::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(CMsgGenericResult, _impl_._cached_size_),
              false,
          },
          &CMsgGenericResult::MergeImpl,
          &CMsgGenericResult::kDescriptorMethods,
          &descriptor_table_econ_5fshared_5fenums_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 39, 2> CMsgGenericResult::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CMsgGenericResult, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CMsgGenericResult_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CMsgGenericResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional string debug_message = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(CMsgGenericResult, _impl_.debug_message_)}},
    // optional uint32 eresult = 1 [default = 2];
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CMsgGenericResult, _impl_.eresult_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(CMsgGenericResult, _impl_.eresult_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 eresult = 1 [default = 2];
    {PROTOBUF_FIELD_OFFSET(CMsgGenericResult, _impl_.eresult_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional string debug_message = 2;
    {PROTOBUF_FIELD_OFFSET(CMsgGenericResult, _impl_.debug_message_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\0\15\0\0\0\0\0"
    "CMsgGenericResult"
    "debug_message"
  }},
};

PROTOBUF_NOINLINE void CMsgGenericResult::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgGenericResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.debug_message_.ClearNonDefaultToEmpty();
    }
    _impl_.eresult_ = 2u;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* CMsgGenericResult::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CMsgGenericResult)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint32 eresult = 1 [default = 2];
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_eresult(), target);
  }

  // optional string debug_message = 2;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_debug_message();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "CMsgGenericResult.debug_message");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgGenericResult)
  return target;
}

::size_t CMsgGenericResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CMsgGenericResult)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string debug_message = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_debug_message());
    }

    // optional uint32 eresult = 1 [default = 2];
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_eresult());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void CMsgGenericResult::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CMsgGenericResult*>(&to_msg);
  auto& from = static_cast<const CMsgGenericResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgGenericResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_debug_message(from._internal_debug_message());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.eresult_ = from._impl_.eresult_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CMsgGenericResult::CopyFrom(const CMsgGenericResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CMsgGenericResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CMsgGenericResult::InternalSwap(CMsgGenericResult* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.debug_message_, &other->_impl_.debug_message_, arena);
        swap(_impl_.eresult_, other->_impl_.eresult_);
}

::google::protobuf::Metadata CMsgGenericResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_econ_5fshared_5fenums_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
