// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: networksystem_protomessages.proto
// Protobuf C++ Version: 5.27.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_networksystem_5fprotomessages_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_networksystem_5fprotomessages_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_networksystem_5fprotomessages_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_networksystem_5fprotomessages_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_networksystem_5fprotomessages_2eproto;
class NetMessageConnectionClosed;
struct NetMessageConnectionClosedDefaultTypeInternal;
extern NetMessageConnectionClosedDefaultTypeInternal _NetMessageConnectionClosed_default_instance_;
class NetMessageConnectionCrashed;
struct NetMessageConnectionCrashedDefaultTypeInternal;
extern NetMessageConnectionCrashedDefaultTypeInternal _NetMessageConnectionCrashed_default_instance_;
class NetMessagePacketEnd;
struct NetMessagePacketEndDefaultTypeInternal;
extern NetMessagePacketEndDefaultTypeInternal _NetMessagePacketEnd_default_instance_;
class NetMessagePacketStart;
struct NetMessagePacketStartDefaultTypeInternal;
extern NetMessagePacketStartDefaultTypeInternal _NetMessagePacketStart_default_instance_;
class NetMessageSplitscreenUserChanged;
struct NetMessageSplitscreenUserChangedDefaultTypeInternal;
extern NetMessageSplitscreenUserChangedDefaultTypeInternal _NetMessageSplitscreenUserChanged_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class NetMessageSplitscreenUserChanged final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NetMessageSplitscreenUserChanged) */ {
 public:
  inline NetMessageSplitscreenUserChanged() : NetMessageSplitscreenUserChanged(nullptr) {}
  ~NetMessageSplitscreenUserChanged() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NetMessageSplitscreenUserChanged(
      ::google::protobuf::internal::ConstantInitialized);

  inline NetMessageSplitscreenUserChanged(const NetMessageSplitscreenUserChanged& from) : NetMessageSplitscreenUserChanged(nullptr, from) {}
  inline NetMessageSplitscreenUserChanged(NetMessageSplitscreenUserChanged&& from) noexcept
      : NetMessageSplitscreenUserChanged(nullptr, std::move(from)) {}
  inline NetMessageSplitscreenUserChanged& operator=(const NetMessageSplitscreenUserChanged& from) {
    CopyFrom(from);
    return *this;
  }
  inline NetMessageSplitscreenUserChanged& operator=(NetMessageSplitscreenUserChanged&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NetMessageSplitscreenUserChanged& default_instance() {
    return *internal_default_instance();
  }
  static inline const NetMessageSplitscreenUserChanged* internal_default_instance() {
    return reinterpret_cast<const NetMessageSplitscreenUserChanged*>(
        &_NetMessageSplitscreenUserChanged_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(NetMessageSplitscreenUserChanged& a, NetMessageSplitscreenUserChanged& b) { a.Swap(&b); }
  inline void Swap(NetMessageSplitscreenUserChanged* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NetMessageSplitscreenUserChanged* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NetMessageSplitscreenUserChanged* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<NetMessageSplitscreenUserChanged>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NetMessageSplitscreenUserChanged& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NetMessageSplitscreenUserChanged& from) { NetMessageSplitscreenUserChanged::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(NetMessageSplitscreenUserChanged* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "NetMessageSplitscreenUserChanged"; }

 protected:
  explicit NetMessageSplitscreenUserChanged(::google::protobuf::Arena* arena);
  NetMessageSplitscreenUserChanged(::google::protobuf::Arena* arena, const NetMessageSplitscreenUserChanged& from);
  NetMessageSplitscreenUserChanged(::google::protobuf::Arena* arena, NetMessageSplitscreenUserChanged&& from) noexcept
      : NetMessageSplitscreenUserChanged(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSlotFieldNumber = 1,
  };
  // optional uint32 slot = 1;
  bool has_slot() const;
  void clear_slot() ;
  ::uint32_t slot() const;
  void set_slot(::uint32_t value);

  private:
  ::uint32_t _internal_slot() const;
  void _internal_set_slot(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:NetMessageSplitscreenUserChanged)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_NetMessageSplitscreenUserChanged_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const NetMessageSplitscreenUserChanged& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t slot_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_networksystem_5fprotomessages_2eproto;
};
// -------------------------------------------------------------------

class NetMessagePacketStart final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:NetMessagePacketStart) */ {
 public:
  inline NetMessagePacketStart() : NetMessagePacketStart(nullptr) {}
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NetMessagePacketStart(
      ::google::protobuf::internal::ConstantInitialized);

  inline NetMessagePacketStart(const NetMessagePacketStart& from) : NetMessagePacketStart(nullptr, from) {}
  inline NetMessagePacketStart(NetMessagePacketStart&& from) noexcept
      : NetMessagePacketStart(nullptr, std::move(from)) {}
  inline NetMessagePacketStart& operator=(const NetMessagePacketStart& from) {
    CopyFrom(from);
    return *this;
  }
  inline NetMessagePacketStart& operator=(NetMessagePacketStart&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NetMessagePacketStart& default_instance() {
    return *internal_default_instance();
  }
  static inline const NetMessagePacketStart* internal_default_instance() {
    return reinterpret_cast<const NetMessagePacketStart*>(
        &_NetMessagePacketStart_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(NetMessagePacketStart& a, NetMessagePacketStart& b) { a.Swap(&b); }
  inline void Swap(NetMessagePacketStart* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NetMessagePacketStart* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NetMessagePacketStart* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<NetMessagePacketStart>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const NetMessagePacketStart& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const NetMessagePacketStart& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "NetMessagePacketStart"; }

 protected:
  explicit NetMessagePacketStart(::google::protobuf::Arena* arena);
  NetMessagePacketStart(::google::protobuf::Arena* arena, const NetMessagePacketStart& from);
  NetMessagePacketStart(::google::protobuf::Arena* arena, NetMessagePacketStart&& from) noexcept
      : NetMessagePacketStart(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ZeroFieldsBase::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:NetMessagePacketStart)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_NetMessagePacketStart_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const NetMessagePacketStart& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_networksystem_5fprotomessages_2eproto;
};
// -------------------------------------------------------------------

class NetMessagePacketEnd final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:NetMessagePacketEnd) */ {
 public:
  inline NetMessagePacketEnd() : NetMessagePacketEnd(nullptr) {}
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NetMessagePacketEnd(
      ::google::protobuf::internal::ConstantInitialized);

  inline NetMessagePacketEnd(const NetMessagePacketEnd& from) : NetMessagePacketEnd(nullptr, from) {}
  inline NetMessagePacketEnd(NetMessagePacketEnd&& from) noexcept
      : NetMessagePacketEnd(nullptr, std::move(from)) {}
  inline NetMessagePacketEnd& operator=(const NetMessagePacketEnd& from) {
    CopyFrom(from);
    return *this;
  }
  inline NetMessagePacketEnd& operator=(NetMessagePacketEnd&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NetMessagePacketEnd& default_instance() {
    return *internal_default_instance();
  }
  static inline const NetMessagePacketEnd* internal_default_instance() {
    return reinterpret_cast<const NetMessagePacketEnd*>(
        &_NetMessagePacketEnd_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(NetMessagePacketEnd& a, NetMessagePacketEnd& b) { a.Swap(&b); }
  inline void Swap(NetMessagePacketEnd* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NetMessagePacketEnd* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NetMessagePacketEnd* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<NetMessagePacketEnd>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const NetMessagePacketEnd& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const NetMessagePacketEnd& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "NetMessagePacketEnd"; }

 protected:
  explicit NetMessagePacketEnd(::google::protobuf::Arena* arena);
  NetMessagePacketEnd(::google::protobuf::Arena* arena, const NetMessagePacketEnd& from);
  NetMessagePacketEnd(::google::protobuf::Arena* arena, NetMessagePacketEnd&& from) noexcept
      : NetMessagePacketEnd(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ZeroFieldsBase::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:NetMessagePacketEnd)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 0, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_NetMessagePacketEnd_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const NetMessagePacketEnd& from_msg);
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  friend struct ::TableStruct_networksystem_5fprotomessages_2eproto;
};
// -------------------------------------------------------------------

class NetMessageConnectionCrashed final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NetMessageConnectionCrashed) */ {
 public:
  inline NetMessageConnectionCrashed() : NetMessageConnectionCrashed(nullptr) {}
  ~NetMessageConnectionCrashed() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NetMessageConnectionCrashed(
      ::google::protobuf::internal::ConstantInitialized);

  inline NetMessageConnectionCrashed(const NetMessageConnectionCrashed& from) : NetMessageConnectionCrashed(nullptr, from) {}
  inline NetMessageConnectionCrashed(NetMessageConnectionCrashed&& from) noexcept
      : NetMessageConnectionCrashed(nullptr, std::move(from)) {}
  inline NetMessageConnectionCrashed& operator=(const NetMessageConnectionCrashed& from) {
    CopyFrom(from);
    return *this;
  }
  inline NetMessageConnectionCrashed& operator=(NetMessageConnectionCrashed&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NetMessageConnectionCrashed& default_instance() {
    return *internal_default_instance();
  }
  static inline const NetMessageConnectionCrashed* internal_default_instance() {
    return reinterpret_cast<const NetMessageConnectionCrashed*>(
        &_NetMessageConnectionCrashed_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(NetMessageConnectionCrashed& a, NetMessageConnectionCrashed& b) { a.Swap(&b); }
  inline void Swap(NetMessageConnectionCrashed* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NetMessageConnectionCrashed* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NetMessageConnectionCrashed* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<NetMessageConnectionCrashed>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NetMessageConnectionCrashed& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NetMessageConnectionCrashed& from) { NetMessageConnectionCrashed::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(NetMessageConnectionCrashed* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "NetMessageConnectionCrashed"; }

 protected:
  explicit NetMessageConnectionCrashed(::google::protobuf::Arena* arena);
  NetMessageConnectionCrashed(::google::protobuf::Arena* arena, const NetMessageConnectionCrashed& from);
  NetMessageConnectionCrashed(::google::protobuf::Arena* arena, NetMessageConnectionCrashed&& from) noexcept
      : NetMessageConnectionCrashed(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kReasonFieldNumber = 1,
  };
  // optional uint32 reason = 1;
  bool has_reason() const;
  void clear_reason() ;
  ::uint32_t reason() const;
  void set_reason(::uint32_t value);

  private:
  ::uint32_t _internal_reason() const;
  void _internal_set_reason(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:NetMessageConnectionCrashed)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_NetMessageConnectionCrashed_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const NetMessageConnectionCrashed& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t reason_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_networksystem_5fprotomessages_2eproto;
};
// -------------------------------------------------------------------

class NetMessageConnectionClosed final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:NetMessageConnectionClosed) */ {
 public:
  inline NetMessageConnectionClosed() : NetMessageConnectionClosed(nullptr) {}
  ~NetMessageConnectionClosed() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NetMessageConnectionClosed(
      ::google::protobuf::internal::ConstantInitialized);

  inline NetMessageConnectionClosed(const NetMessageConnectionClosed& from) : NetMessageConnectionClosed(nullptr, from) {}
  inline NetMessageConnectionClosed(NetMessageConnectionClosed&& from) noexcept
      : NetMessageConnectionClosed(nullptr, std::move(from)) {}
  inline NetMessageConnectionClosed& operator=(const NetMessageConnectionClosed& from) {
    CopyFrom(from);
    return *this;
  }
  inline NetMessageConnectionClosed& operator=(NetMessageConnectionClosed&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NetMessageConnectionClosed& default_instance() {
    return *internal_default_instance();
  }
  static inline const NetMessageConnectionClosed* internal_default_instance() {
    return reinterpret_cast<const NetMessageConnectionClosed*>(
        &_NetMessageConnectionClosed_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(NetMessageConnectionClosed& a, NetMessageConnectionClosed& b) { a.Swap(&b); }
  inline void Swap(NetMessageConnectionClosed* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NetMessageConnectionClosed* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NetMessageConnectionClosed* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<NetMessageConnectionClosed>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const NetMessageConnectionClosed& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const NetMessageConnectionClosed& from) { NetMessageConnectionClosed::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(NetMessageConnectionClosed* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "NetMessageConnectionClosed"; }

 protected:
  explicit NetMessageConnectionClosed(::google::protobuf::Arena* arena);
  NetMessageConnectionClosed(::google::protobuf::Arena* arena, const NetMessageConnectionClosed& from);
  NetMessageConnectionClosed(::google::protobuf::Arena* arena, NetMessageConnectionClosed&& from) noexcept
      : NetMessageConnectionClosed(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kReasonFieldNumber = 1,
  };
  // optional uint32 reason = 1;
  bool has_reason() const;
  void clear_reason() ;
  ::uint32_t reason() const;
  void set_reason(::uint32_t value);

  private:
  ::uint32_t _internal_reason() const;
  void _internal_set_reason(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:NetMessageConnectionClosed)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_NetMessageConnectionClosed_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const NetMessageConnectionClosed& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t reason_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_networksystem_5fprotomessages_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// NetMessageSplitscreenUserChanged

// optional uint32 slot = 1;
inline bool NetMessageSplitscreenUserChanged::has_slot() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void NetMessageSplitscreenUserChanged::clear_slot() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.slot_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint32_t NetMessageSplitscreenUserChanged::slot() const {
  // @@protoc_insertion_point(field_get:NetMessageSplitscreenUserChanged.slot)
  return _internal_slot();
}
inline void NetMessageSplitscreenUserChanged::set_slot(::uint32_t value) {
  _internal_set_slot(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:NetMessageSplitscreenUserChanged.slot)
}
inline ::uint32_t NetMessageSplitscreenUserChanged::_internal_slot() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.slot_;
}
inline void NetMessageSplitscreenUserChanged::_internal_set_slot(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.slot_ = value;
}

// -------------------------------------------------------------------

// NetMessageConnectionClosed

// optional uint32 reason = 1;
inline bool NetMessageConnectionClosed::has_reason() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void NetMessageConnectionClosed::clear_reason() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reason_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint32_t NetMessageConnectionClosed::reason() const {
  // @@protoc_insertion_point(field_get:NetMessageConnectionClosed.reason)
  return _internal_reason();
}
inline void NetMessageConnectionClosed::set_reason(::uint32_t value) {
  _internal_set_reason(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:NetMessageConnectionClosed.reason)
}
inline ::uint32_t NetMessageConnectionClosed::_internal_reason() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reason_;
}
inline void NetMessageConnectionClosed::_internal_set_reason(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reason_ = value;
}

// -------------------------------------------------------------------

// NetMessageConnectionCrashed

// optional uint32 reason = 1;
inline bool NetMessageConnectionCrashed::has_reason() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void NetMessageConnectionCrashed::clear_reason() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reason_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint32_t NetMessageConnectionCrashed::reason() const {
  // @@protoc_insertion_point(field_get:NetMessageConnectionCrashed.reason)
  return _internal_reason();
}
inline void NetMessageConnectionCrashed::set_reason(::uint32_t value) {
  _internal_set_reason(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:NetMessageConnectionCrashed.reason)
}
inline ::uint32_t NetMessageConnectionCrashed::_internal_reason() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.reason_;
}
inline void NetMessageConnectionCrashed::_internal_set_reason(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.reason_ = value;
}

// -------------------------------------------------------------------

// NetMessagePacketStart

// -------------------------------------------------------------------

// NetMessagePacketEnd

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_networksystem_5fprotomessages_2eproto_2epb_2eh
